---
- name: Add Crowdin GPG apt Key
  apt_key:
    url: "{{ crowdin_apt_gpg_key }}"
    state: present

- name: Add Crowdin Repository
  apt_repository:
    repo: "{{ crowdin_apt_repository }}"
    state: present
    update_cache: true

- name: Update apt and install crowdin3
  apt:
    name: 
      - crowdin3
    state: latest
    update_cache: false