- name: Set hosts Kibana
  lineinfile:
      path: /etc/hosts
      state: present
      insertafter: EOF
      regexp: 127.0.0.1 kibana
      line: 127.0.0.1 kibana

- name: Set hosts Keycloak
  lineinfile:
      path: /etc/hosts
      state: present
      insertafter: EOF
      regexp: 127.0.0.1 keycloak
      line: 127.0.0.1 keycloak

- name: Set hosts Dispatcher
  lineinfile:
      path: /etc/hosts
      state: present
      insertafter: EOF
      regexp: 127.0.0.1 dispatcher
      line: 127.0.0.1 dispatcher