- name: Set hosts Dashboard Local
  lineinfile:
      path: /etc/hosts
      state: present
      insertafter: EOF
      regexp: 127.0.0.1 app.audiens.local postgres kibana
      line: 127.0.0.1 app.audiens.local postgres kibana
